const groups=[
 {name:'Pathankot',code:'PTK',route:'Pathankot–Jammu BG section',type:'Broad gauge',image:'pathankot-depot.png',imageAlt:'Pathankot Junction railway station',imageCredit:'Image provided by user',imageSource:'pathankot-depot.png',stations:[['Pathankot Junction','PTK'],['Pathankot Cantt','PTKC'],['Madhopur Punjab','MDPB'],['Sujanpur','SJNP'],['Kathua','KTHU'],['Budhi','BDHY'],['Chhan Arorian','CHNR'],['Chak Dayala','CKDL'],['Hira Nagar','HRNR'],['Ghagwal','GHGL'],['Samba','SMBX'],['Basantar Block Hut','BHBT'],['Vijaypur Jammu','VJPJ'],['Bari Brahman','BBMN']]},
 {name:'Jammu Tawi',code:'JAT',route:'Jammu–Udhampur–Katra section',type:'Broad gauge',image:'jammu-tawi-depot.png',imageAlt:'Jammu Tawi railway station',imageCredit:'Image provided by user',imageSource:'jammu-tawi-depot.png',stations:[['Jammu Tawi','JAT'],['Bajalta','BLA'],['Sangar','SGRR'],['Manwal','MNVL'],['Ram Nagar Jammu','RMJK'],['Udhampur','UHP'],['Chak Rakhwal','CRWL'],['Shri Mata Vaishno Devi Katra','SVDK']]},
 {name:'USBRL',code:'SVDK / MCTM',route:'Katra–Reasi–MCTM–Sangaldan–Banihal',type:'USBRL',image:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Katra_railway_station.jpg/960px-Katra_railway_station.jpg',imageAlt:'Entrance of Shri Mata Vaishno Devi Katra railway station',imageCredit:'Lillottama · CC BY-SA 4.0',imageSource:'https://commons.wikimedia.org/wiki/File:Katra_railway_station.jpg',stations:[['Shri Mata Vaishno Devi Katra','SVDK'],['Martyr Captain Tushar Mahajan Udhampur','MCTM'],['Reasi','REAI'],['Bakkal','BAKK'],['Dugga','DUGA'],['Sawalkote','SWKE'],['Sangaldan','SGDN'],['Sumber','SMBR'],['Khari','KARI'],['Banihal','BAHL']]},
 {name:'Banihal',code:'BAHL',route:'Banihal–Srinagar section',type:'Kashmir Valley',image:'banihal-depot.png',imageAlt:'Banihal railway station with mountains in the background',imageCredit:'Image provided by user',imageSource:'banihal-depot.png',stations:[['Banihal','BAHL'],['Hiller Shahabad','HRSB'],['Qazigund','QG'],['Sadura','SDUA'],['Anantnag','ANT'],['Bijbehara','BJBA'],['Panzgom','PJGM'],['Awantipura','ATPA'],['Kakapora','KAPE'],['Pampore','PMPE'],['Srinagar','SINA']]},
 {name:'Budgam',code:'BDGM',route:'Budgam–Baramulla section',type:'Kashmir Valley',image:'budgam-depot.png',imageAlt:'Budgam railway station and train with mountains in the background',imageCredit:'Image provided by user',imageSource:'budgam-depot.png',stations:[['Budgam','BDGM'],['Mazhom','MZMA'],['Pattan','PTTN'],['Hamre','HME'],['Sopore','SXZM'],['Baramulla','BRML']]},
 {name:'Pathankot Narrow Gauge',code:'PTK/NG',route:'Pathankot–Joginder Nagar · approx. 164 km',type:'Kangra Valley narrow gauge',image:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Kangra_valley_rail.jpg/960px-Kangra_valley_rail.jpg',imageAlt:'Pathankot to Baijnath narrow gauge train on the Kangra Valley line',imageCredit:'GKarunakar · CC BY-SA 3.0',imageSource:'https://commons.wikimedia.org/wiki/File:Kangra_valley_rail.jpg',stations:[['Pathankot','PTK'],['Pathankot Cantt','PTKC'],['Kandrori','KNDI'],['Kandwal','KAWL'],['Nurpur Road','NUPR'],['Kopar Lahar','KPLR'],['Guler','GULR'],['Nagrota Suriyan','NGRS'],['Nandpur Bhatauli','NDBT'],['Jawanwala Shahr','JWLS'],['Harsar Dehri','HRDR'],['Dera Gopipur / related NG locations',''],['Jwalamukhi Road','JMKR'],['Chauntra Bhater','CTZ'],['Joginder Nagar','JDNX'],['Kangra','KGRA'],['Kangra Mandir','KGMR'],['Nagrota',''],['Additional Kangra Valley locations','']]},
 {name:'Baijnath Paprola',code:'BJPL/NG',route:'Kangra Valley narrow gauge',type:'Kangra Valley narrow gauge',image:'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Baijnathpaprola-station.jpg/960px-Baijnathpaprola-station.jpg',imageAlt:'Baijnath Paprola railway station',imageCredit:'GKarunakar · CC BY-SA 3.0',imageSource:'https://commons.wikimedia.org/wiki/File:Baijnathpaprola-station.jpg',stations:[['Baijnath Paprola','BJPL'],['Baijnath Mandir','BJMR'],['Palampur Himachal','PLMX'],['Panchrukhi','PHRH'],['Sulah Himachal Pradesh','SLHP'],['Majhairan Himachal','MNHL'],['Megh Raj Pura','MGRP'],['Paror','PRAR'],['Samloti','SMLT'],['Kangra','KGRA'],['Kangra Mandir','KGMR'],['Barial Himachal','BRHL'],['Bharmar','BRMR'],['Talara','TLRA'],['Tripal Halt','TRPL'],['Lunsu Halt','LNS']]}
];
// A station belongs to one depot section only. Keep its first listed occurrence.
const seenStationNames=new Set(),seenStationCodes=new Set();
for(const group of groups){group.stations=group.stations.filter(([name,code])=>{const stationName=name.trim().toLocaleLowerCase().replace(/\s+/g,' '),stationCode=code.trim().toLocaleUpperCase();if(seenStationNames.has(stationName)||(stationCode&&seenStationCodes.has(stationCode)))return false;seenStationNames.add(stationName);if(stationCode)seenStationCodes.add(stationCode);return true})}
const subcolumns=['Substation','HT Panel','LT Panel','APFC Panel','Transformers','D G Set','Pumps','Lifts','Escalators','CLS Panel'];
const scheduleIntervals=['1M','3M','HY','1Y','5Y'];
const grid=document.querySelector('#depotGrid'),input=document.querySelector('#searchInput'),count=document.querySelector('#resultCount'),stationTotal=document.querySelector('#stationTotal'),resultLabel=document.querySelector('#resultLabel'),sectionFilters=document.querySelector('#sectionFilters'),clearSearch=document.querySelector('#clearSearch');let activeSectionFilter='all';
const scheduleStore={};try{Object.assign(scheduleStore,JSON.parse(localStorage.getItem('depotSchedules')||'{}'))}catch{}
const assetCountStore={};try{Object.assign(assetCountStore,JSON.parse(localStorage.getItem('depotAssetCounts')||'{}'))}catch{}
const assetUnitStore={};try{Object.assign(assetUnitStore,JSON.parse(localStorage.getItem('depotAssetUnits')||'{}'))}catch{}
const dialog=document.querySelector('#scheduleDialog'),tabs=document.querySelector('.schedule-tabs'),notes=document.querySelector('#scheduleNotes'),lastDone=document.querySelector('#lastDone'),nextDue=document.querySelector('#nextDue'),scheduleLocation=document.querySelector('#scheduleLocation'),scheduleSSE=document.querySelector('#scheduleSSE'),scheduleJE=document.querySelector('#scheduleJE'),assetRating=document.querySelector('#assetRating'),assetManager=document.querySelector('#assetManager'),unitScheduleEditor=document.querySelector('#unitScheduleEditor'),assetUnitList=document.querySelector('#assetUnitList');let activeSchedule=null,activeInterval=0,activeUnitId=null,scheduleDraft=[];
const trackerLists={completed:document.querySelector('#completedSchedules'),scheduled:document.querySelector('#scheduledSchedules'),overdue:document.querySelector('#overdueSchedules')};
function scheduleKey(){return `${activeSchedule.group}|${activeSchedule.station}|${activeSchedule.equipment}`}
function emptySchedule(){return {location:'',lastDone:'',nextDue:'',sse:'',je:'',notes:''}}
function normalizeSchedule(value){if(typeof value==='string')return {...emptySchedule(),notes:value};return {...emptySchedule(),...(value&&typeof value==='object'?value:{})}}
function scheduleHasData(value){return !!(value&&(typeof value==='string'?value.trim():value.location?.trim()||value.lastDone||value.nextDue||value.sse?.trim()||value.je?.trim()||value.notes?.trim()))}
function makeUnitId(){return `unit-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function persistUnits(key){assetCountStore[key]=(assetUnitStore[key]||[]).length;try{localStorage.setItem('depotAssetUnits',JSON.stringify(assetUnitStore));localStorage.setItem('depotAssetCounts',JSON.stringify(assetCountStore))}catch{}}
function unitsForKey(key,create=false){if(Array.isArray(assetUnitStore[key]))return assetUnitStore[key];const legacySchedules=scheduleStore[key],legacyCount=Math.max(0,Math.floor(Number(assetCountStore[key])||0)),hasLegacySchedule=Array.isArray(legacySchedules)&&legacySchedules.some(scheduleHasData),count=Math.max(legacyCount,hasLegacySchedule?1:0);if(!count){if(create)assetUnitStore[key]=[];return create?assetUnitStore[key]:[]}const equipment=key.split('|').at(-1);assetUnitStore[key]=Array.from({length:count},(_,index)=>({id:makeUnitId(),label:`${equipment} ${index+1}`,schedules:index===0&&hasLegacySchedule?legacySchedules.map(normalizeSchedule):Array.from({length:scheduleIntervals.length},emptySchedule)}));persistUnits(key);return assetUnitStore[key]}
function formatScheduleDate(value){if(!value)return '—';const date=new Date(`${value}T00:00:00Z`);return Number.isNaN(date.getTime())?escapeHtml(value):new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(date)}
function dueStatus(value){if(!value)return 'No due date';const now=new Date(),today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;return value<today?'Overdue':value===today?'Due today':'Upcoming'}
function renderAssetUnits(){const units=unitsForKey(scheduleKey());assetUnitList.innerHTML=units.length?units.map(unit=>{const saved=(unit.schedules||[]).filter(scheduleHasData).length,timeline=(unit.schedules||[]).map((value,index)=>({record:normalizeSchedule(value),index})).filter(({record})=>scheduleHasData(record)),timelineMarkup=timeline.length?timeline.map(({record,index})=>{const status=record.nextDue?dueStatus(record.nextDue):record.lastDone?'Completed':'No due date';return `<button type="button" class="unit-timeline-entry ${status==='Overdue'?'overdue':''}" data-edit-unit="${unit.id}" data-edit-interval="${index}"><span class="timeline-interval">${escapeHtml(scheduleIntervals[index])}</span><span class="timeline-dates"><span>Last done <b>${formatScheduleDate(record.lastDone)}</b></span><span>Next due <b>${formatScheduleDate(record.nextDue)}</b></span></span><span class="timeline-location">${record.location?`Location: ${escapeHtml(record.location)}`:'Location not set'}</span><span class="timeline-status">${status}</span><span class="timeline-edit">Edit ↗</span></button>`}).join(''):'<p class="empty-unit-timeline">No saved schedules yet. Open Edit schedules to add the first one.</p>';return `<section class="asset-unit-card" data-asset-unit="${escapeHtml(unit.id)}"><div class="asset-unit-row"><label><span>Asset name / rating</span><input type="text" value="${escapeHtml(unit.label)}" data-unit-label="${unit.id}" aria-label="Asset name or rating"></label><button type="button" class="unit-schedule-button" data-edit-unit="${unit.id}">Edit schedules <small>${saved}/5 intervals</small></button><button type="button" class="remove-asset-unit" data-remove-unit="${unit.id}" aria-label="Remove ${escapeHtml(unit.label)}">×</button></div><p class="asset-rating-summary">Rating: ${unit.rating?escapeHtml(unit.rating):'Not set'}</p><div class="unit-timeline"><h3>Saved schedules · timeline</h3>${timelineMarkup}</div></section>`}).join(''):'<p class="no-assets-yet">No individual assets added yet. Add each substation, panel, pump, or other unit separately.</p>';if(typeof refreshInventoryAlerts==='function')refreshInventoryAlerts()}
function renderScheduleTracker(){const entries=[];for(const group of groups)for(const [station] of group.stations)for(const equipment of subcolumns){const key=`${group.code}|${station}|${equipment}`;for(const unit of unitsForKey(key))for(let interval=0;interval<scheduleIntervals.length;interval++){const record=normalizeSchedule(unit.schedules?.[interval]);if(scheduleHasData(record))entries.push({group,station,equipment,unit,interval,record})}}const today=(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`})();const lists={completed:entries.filter(item=>!!item.record.lastDone),scheduled:entries.filter(item=>!!item.record.nextDue&&item.record.nextDue>=today),overdue:entries.filter(item=>!!item.record.nextDue&&item.record.nextDue<today)};for(const [name,list] of Object.entries(lists)){document.querySelector(`#${name}Count`).textContent=String(list.length).padStart(2,'0');trackerLists[name].innerHTML=list.length?list.sort((a,b)=>(a.record.nextDue||'9999').localeCompare(b.record.nextDue||'9999')).map(item=>`<button type="button" class="tracker-entry ${name==='overdue'?'tracker-entry-overdue':''}" data-tracker-entry data-group="${item.group.code}" data-station="${escapeHtml(item.station)}" data-equipment="${escapeHtml(item.equipment)}" data-unit="${item.unit.id}" data-interval="${item.interval}"><span class="tracker-station">${escapeHtml(item.station)} <small>${escapeHtml(item.group.code)}</small></span><span class="tracker-asset">${escapeHtml(item.equipment)} · ${escapeHtml(item.unit.label)}</span><span class="tracker-interval">${escapeHtml(scheduleIntervals[item.interval])}</span><span class="tracker-dates"><span>Last done <b>${formatScheduleDate(item.record.lastDone)}</b></span><span>Next due <b>${formatScheduleDate(item.record.nextDue)}</b></span></span>${name==='overdue'?`<span class="tracker-alert">OVERDUE · ${dueStatus(item.record.nextDue)}</span>`:''}</button>`).join(''):`<p class="tracker-empty">No ${name==='overdue'?'overdue reminders':name+' schedules'}.</p>`}}
function calculateNextDue(value,interval){
 const months=[1,3,6,12,60][interval];
 if(!/^\d{4}-\d{2}-\d{2}$/.test(value||'')||!months)return '';
 const date=new Date(`${value}T00:00:00Z`);
 if(Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==value)return '';
 const day=date.getUTCDate();
 date.setUTCDate(1);
 date.setUTCMonth(date.getUTCMonth()+months);
 const endOfMonth=new Date(date.getTime());
 endOfMonth.setUTCMonth(endOfMonth.getUTCMonth()+1,0);
 date.setUTCDate(Math.min(day,endOfMonth.getUTCDate()));
 return date.getUTCFullYear()>9999?'':date.toISOString().slice(0,10);
}
function updateAutomaticNextDue(){nextDue.value=calculateNextDue(lastDone.value,activeInterval)}
lastDone.addEventListener('input',updateAutomaticNextDue);
lastDone.addEventListener('change',updateAutomaticNextDue);
function collectInterval(){scheduleDraft[activeInterval]={location:scheduleLocation.value.trim(),lastDone:lastDone.value,nextDue:nextDue.value,sse:scheduleSSE.value.trim(),je:scheduleJE.value.trim(),notes:notes.value}}
function showInterval(){tabs.querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('active',i===activeInterval);b.setAttribute('aria-selected',i===activeInterval?'true':'false')});const record=scheduleDraft[activeInterval]||emptySchedule();scheduleLocation.value=record.location||'';lastDone.value=record.lastDone||'';nextDue.value=record.nextDue||calculateNextDue(lastDone.value,activeInterval);scheduleSSE.value=record.sse||'';scheduleJE.value=record.je||'';notes.value=record.notes||''}
function openSchedule(button){activeSchedule={group:button.dataset.group,station:button.dataset.station,equipment:button.dataset.equipment};document.querySelector('#scheduleTitle').textContent=`${activeSchedule.equipment} Assets`;document.querySelector('#scheduleContext').textContent=`${activeSchedule.station} · ${activeSchedule.group}`;assetManager.hidden=false;unitScheduleEditor.hidden=true;renderAssetUnits();dialog.showModal()}
function editUnit(unitId,intervalIndex=0){const units=unitsForKey(scheduleKey()),unit=units.find(item=>item.id===unitId);if(!unit)return;activeUnitId=unitId;activeInterval=intervalIndex;scheduleDraft=Array.from({length:scheduleIntervals.length},(_,i)=>normalizeSchedule(unit.schedules?.[i]));document.querySelector('#activeAssetName').textContent=unit.label;assetRating.value=unit.rating||'';assetManager.hidden=true;unitScheduleEditor.hidden=false;tabs.innerHTML=scheduleIntervals.map((label,i)=>`<button type="button" role="tab" aria-selected="${i===activeInterval}" class="${i===activeInterval?'active':''}">${label}</button>`).join('');tabs.querySelectorAll('button').forEach((tab,i)=>tab.addEventListener('click',()=>{collectInterval();activeInterval=i;showInterval()}));showInterval()}
function saveSchedule(){collectInterval();const key=scheduleKey(),unit=unitsForKey(key).find(item=>item.id===activeUnitId);if(unit){unit.rating=assetRating.value.trim();unit.schedules=scheduleDraft.map(normalizeSchedule);persistUnits(key)}unitScheduleEditor.hidden=true;assetManager.hidden=false;renderAssetUnits();render()}
function normalizeSearch(value){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase()}
function render(){
 const query=normalizeSearch(input.value),tokens=query.split(/\s+/).filter(Boolean);
 const rows=groups.map(group=>{const metadata=normalizeSearch(`${group.name} ${group.code} ${group.route} ${group.type}`),matchedStations=group.stations.filter(([name,code])=>tokens.every(token=>normalizeSearch(`${name} ${code}`).includes(token))),metadataMatches=tokens.length>0&&tokens.every(token=>metadata.includes(token)),stations=matchedStations.length?matchedStations:group.stations;return {group,stations,matchedStations,metadataMatches}}).filter(({group,matchedStations,metadataMatches})=>(activeSectionFilter==='all'||group.type===activeSectionFilter)&&(!tokens.length||matchedStations.length>0||metadataMatches));
 const total=rows.reduce((sum,row)=>sum+row.stations.length,0),searching=tokens.length>0;
 count.textContent=String(rows.length).padStart(2,'0');resultLabel.textContent=rows.length===1?'group':'groups';stationTotal.textContent=searching?`${total} matching station${total===1?'':'s'} · ${subcolumns.length} asset columns each`:`${total} station entries · ${subcolumns.length} asset columns each`;clearSearch.hidden=!input.value;
 grid.innerHTML=rows.length?rows.map(({group:g,stations},i)=>`<article class="depot-card station-card"><div class="card-image"><img loading="lazy" src="${g.image}" alt="${g.imageAlt}"><span class="availability">${g.type}</span><span class="card-arrow">${String(i+1).padStart(2,'0')}</span><a class="image-credit" href="${g.imageSource}" target="_blank" rel="noopener noreferrer" aria-label="Photo: ${g.imageCredit}. Opens the image source">${g.imageCredit} ↗</a></div><div class="card-body"><span class="card-region">${g.code}</span><h3>${g.name}</h3><p class="card-address">${g.route}</p><details class="station-details"><summary><span>${stations.length} ${stations.length===1?'station':'stations'} · ${subcolumns.length} sub-columns</span><span class="details-action">Show station table <b>＋</b></span></summary><p class="station-table-help">Click an equipment cell to add individual units, then open each unit to edit its separate five-interval schedule.</p><div class="station-table-scroll"><table class="station-table"><thead><tr><th>Station</th><th>Code</th>${subcolumns.map(col=>`<th>${col}</th>`).join('')}</tr></thead><tbody>${stations.map(([name,code])=>`<tr><th scope="row">${name}</th><td><code>${code||'—'}</code></td>${subcolumns.map(col=>{const key=`${g.code}|${name}|${col}`,units=unitsForKey(key),savedSchedules=units.reduce((total,unit)=>total+(unit.schedules||[]).filter(scheduleHasData).length,0);return `<td class="schedule-cell"><button type="button" class="schedule-cell-button ${savedSchedules?'has-schedule':''}" data-group="${g.code}" data-station="${name}" data-equipment="${col}" aria-label="Manage individual ${col} units and schedules at ${name}"><span class="asset-count">${units.length||'—'}</span><small>${units.length?`${units.length} units · ${savedSchedules} schedules`:'Add individual units'}</small></button></td>`}).join('')}</tr>`).join('')}</tbody></table></div></details></div></article>`).join(''):'<div class="empty-state"><strong>No matching depots or stations.</strong><br>Try a station name, station code, route, or clear the section filter.</div>';renderScheduleTracker();
}
const sectionTypes=['all',...new Set(groups.map(group=>group.type))];sectionFilters.innerHTML=sectionTypes.map((type,index)=>`<button type="button" class="filter-chip ${index===0?'selected':''}" data-section="${type}" aria-pressed="${index===0}">${index===0?'All sections':type}<span>${index===0?groups.length:groups.filter(group=>group.type===type).length}</span></button>`).join('');sectionFilters.addEventListener('click',event=>{const button=event.target.closest('[data-section]');if(!button)return;activeSectionFilter=button.dataset.section;sectionFilters.querySelectorAll('[data-section]').forEach(chip=>{const selected=chip===button;chip.classList.toggle('selected',selected);chip.setAttribute('aria-pressed',String(selected))});render()});input.addEventListener('input',render);clearSearch.addEventListener('click',()=>{input.value='';render();input.focus()});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.focus()}if(e.key==='Escape'&&document.activeElement===input&&input.value){input.value='';render()}});render();
grid.addEventListener('click',e=>{const button=e.target.closest('.schedule-cell-button');if(button)openSchedule(button)});document.querySelector('#scheduleTracker').addEventListener('click',event=>{const entry=event.target.closest('[data-tracker-entry]');if(!entry)return;activeSchedule={group:entry.dataset.group,station:entry.dataset.station,equipment:entry.dataset.equipment};document.querySelector('#scheduleTitle').textContent=`${activeSchedule.equipment} Assets`;document.querySelector('#scheduleContext').textContent=`${activeSchedule.station} · ${activeSchedule.group}`;assetManager.hidden=false;unitScheduleEditor.hidden=true;dialog.showModal();editUnit(entry.dataset.unit,Number(entry.dataset.interval))});document.querySelector('#addAssetForm').addEventListener('submit',event=>{event.preventDefault();const field=document.querySelector('#newAssetName'),label=field.value.trim();if(!label)return;const key=scheduleKey(),units=unitsForKey(key,true);units.push({id:makeUnitId(),label,schedules:Array.from({length:scheduleIntervals.length},emptySchedule)});persistUnits(key);field.value='';renderAssetUnits();render()});assetUnitList.addEventListener('click',event=>{const edit=event.target.closest('[data-edit-unit]');if(edit){editUnit(edit.dataset.editUnit,Number(edit.dataset.editInterval||0));return}const remove=event.target.closest('[data-remove-unit]');if(remove){const key=scheduleKey(),units=unitsForKey(key),unit=units.find(item=>item.id===remove.dataset.removeUnit);if(!unit||!confirm(`Remove ${unit.label} and its saved schedules?`))return;assetUnitStore[key]=units.filter(item=>item.id!==unit.id);persistUnits(key);renderAssetUnits();render()}});assetUnitList.addEventListener('change',event=>{const field=event.target.closest('[data-unit-label]');if(!field)return;const unit=unitsForKey(scheduleKey()).find(item=>item.id===field.dataset.unitLabel);if(unit){unit.label=field.value.trim()||activeSchedule.equipment;persistUnits(scheduleKey());renderAssetUnits();render()}});document.querySelector('#backToAssets').addEventListener('click',saveSchedule);document.querySelector('#saveSchedule').addEventListener('click',saveSchedule);document.querySelector('#clearSchedule').addEventListener('click',()=>{scheduleLocation.value='';lastDone.value='';nextDue.value='';scheduleSSE.value='';scheduleJE.value='';notes.value='';scheduleDraft[activeInterval]=emptySchedule();saveSchedule()});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});setInterval(() => renderScheduleTracker(),60000);
const renderScheduleTrackerBase = renderScheduleTracker;
renderScheduleTracker = function(){ renderScheduleTrackerBase(); document.dispatchEvent(new CustomEvent("schedules-updated")); };
